name: build

on:
  push:
    branches:
    tags:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

      - name: remote deployment from master
        if: ${{ github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' }}
        env:
          UPDATER_KEY: ${{ secrets.UPDATER_KEY }}
        run: curl https://radio-t.com/updater/update/tg-spam-samples/${UPDATER_KEY}
